-- ========================================
-- DAD JOKE CENTRAL - Seed Data
-- ========================================

-- Insert Categories
INSERT INTO categories (slug, name, icon, description, sort_order) VALUES
('classic', 'Classic', '👴', 'Timeless groaners that never get old', 1),
('food', 'Food', '🍕', 'Tasty puns to satisfy your humor appetite', 2),
('tech', 'Tech', '💻', 'Nerdy humor for the digitally inclined', 3),
('animals', 'Animals', '🐶', 'Wild jokes from the animal kingdom', 4),
('work', 'Work', '💼', 'Office humor to survive the 9-to-5', 5),
('holiday', 'Holiday', '🎄', 'Seasonal fun for every occasion', 6),
('science', 'Science', '🔬', 'Lab laughs and scientific silliness', 7),
('sports', 'Sports', '⚽', 'Game day grins and athletic puns', 8),
('music', 'Music', '🎸', 'Musical puns that hit all the right notes', 9),
('family', 'Family', '👨‍👩‍👧', 'Wholesome home humor', 10);

-- Insert Jokes (using slug to reference category)
-- Classic jokes
INSERT INTO jokes (category_id, setup, punchline, groan_count, laugh_count, eyeroll_count)
SELECT c.id, j.setup, j.punchline,
       floor(random() * 3000 + 500)::int,
       floor(random() * 2000 + 300)::int,
       floor(random() * 4000 + 800)::int
FROM categories c
CROSS JOIN (VALUES
    ('classic', 'Why don''t scientists trust atoms?', 'Because they make up everything!'),
    ('classic', 'What do you call a fake noodle?', 'An impasta!'),
    ('classic', 'Why did the scarecrow win an award?', 'Because he was outstanding in his field!'),
    ('classic', 'I''m reading a book about anti-gravity.', 'It''s impossible to put down!'),
    ('classic', 'Why don''t eggs tell jokes?', 'They''d crack each other up!'),
    ('classic', 'What do you call a bear with no teeth?', 'A gummy bear!'),
    ('classic', 'Why did the bicycle fall over?', 'Because it was two-tired!'),
    ('classic', 'What''s orange and sounds like a parrot?', 'A carrot!'),
    ('classic', 'I used to hate facial hair.', 'But then it grew on me.'),
    ('classic', 'What did the ocean say to the beach?', 'Nothing, it just waved.'),
    ('classic', 'Why can''t you hear a pterodactyl going to the bathroom?', 'Because the P is silent!'),
    ('classic', 'I would tell you a construction joke.', 'But I''m still working on it.'),
    ('classic', 'What do you call a can opener that doesn''t work?', 'A can''t opener!'),
    ('classic', 'Why do fathers take an extra pair of socks when they go golfing?', 'In case they get a hole in one!'),
    ('classic', 'What do you call a man with a rubber toe?', 'Roberto!'),

    ('food', 'What do you call cheese that isn''t yours?', 'Nacho cheese!'),
    ('food', 'Why did the coffee file a police report?', 'It got mugged!'),
    ('food', 'What did the grape say when it got stepped on?', 'Nothing, it just let out a little wine!'),
    ('food', 'Why don''t bananas ever feel lonely?', 'Because they hang out in bunches!'),
    ('food', 'What do you call a sad strawberry?', 'A blueberry!'),
    ('food', 'What do you call a fake steak?', 'A mis-steak!'),
    ('food', 'Why did the tomato turn red?', 'Because it saw the salad dressing!'),
    ('food', 'What do you call a sleeping pizza?', 'A piZZZZa!'),
    ('food', 'Why did the cookie go to the doctor?', 'Because it was feeling crummy!'),
    ('food', 'What''s a potato''s favorite day?', 'Fry-day!'),
    ('food', 'Why do mushrooms get invited to all the parties?', 'Because they''re such fungi!'),
    ('food', 'What do you call an avocado that''s been blessed?', 'Holy guacamole!'),
    ('food', 'Why did the lemon stop rolling down the hill?', 'It ran out of juice!'),
    ('food', 'What''s a ghost''s favorite fruit?', 'Boo-berries!'),
    ('food', 'Why do seagulls fly over the sea?', 'Because if they flew over the bay, they''d be bagels!'),

    ('tech', 'Why do programmers prefer dark mode?', 'Because light attracts bugs!'),
    ('tech', 'Why was the computer cold?', 'It left its Windows open!'),
    ('tech', 'What''s a computer''s favorite snack?', 'Microchips!'),
    ('tech', 'Why did the AI cross the road?', 'To optimize the chicken''s path!'),
    ('tech', 'How does a computer get drunk?', 'It takes screenshots!'),
    ('tech', 'Why do Java developers wear glasses?', 'Because they don''t C#!'),
    ('tech', 'What''s a robot''s favorite type of music?', 'Heavy metal!'),
    ('tech', 'Why did the PowerPoint presentation cross the road?', 'To get to the other slide!'),
    ('tech', 'What do you call a computer that sings?', 'A-Dell!'),
    ('tech', 'Why was the JavaScript developer sad?', 'Because he didn''t Node how to Express himself!'),
    ('tech', 'What''s a computer''s least favorite food?', 'Spam!'),
    ('tech', 'Why did the developer go broke?', 'Because he used up all his cache!'),
    ('tech', 'What do you call 8 hobbits?', 'A hobbyte!'),
    ('tech', 'Why do programmers always mix up Halloween and Christmas?', 'Because Oct 31 = Dec 25!'),
    ('tech', 'There are only 10 types of people in the world.', 'Those who understand binary and those who don''t.'),

    ('animals', 'What do you call a fish without eyes?', 'A fsh!'),
    ('animals', 'Why don''t oysters share?', 'Because they''re shellfish!'),
    ('animals', 'What do you call an alligator in a vest?', 'An investigator!'),
    ('animals', 'Why don''t cats play poker in the jungle?', 'Too many cheetahs!'),
    ('animals', 'What do you call a dog that does magic?', 'A Labracadabrador!'),
    ('animals', 'Why do cows wear bells?', 'Because their horns don''t work!'),
    ('animals', 'What do you call a sleeping dinosaur?', 'A dino-snore!'),
    ('animals', 'What do you call a fly without wings?', 'A walk!'),
    ('animals', 'Why do bees have sticky hair?', 'Because they use honeycombs!'),
    ('animals', 'What do you call a lazy kangaroo?', 'A pouch potato!'),
    ('animals', 'Why don''t elephants use computers?', 'Because they''re afraid of the mouse!'),
    ('animals', 'What do you call a cow with no legs?', 'Ground beef!'),
    ('animals', 'What do you call a deer with no eyes?', 'No eye-deer!'),
    ('animals', 'What do you call a snake that''s 3.14 meters long?', 'A π-thon!'),
    ('animals', 'What do you call a fish that wears a crown?', 'A king fish!'),

    ('work', 'Why did the employee get fired from the calendar factory?', 'They took too many days off!'),
    ('work', 'Why did the math book look so sad?', 'Because it had too many problems!'),
    ('work', 'What''s the best thing about elevator jokes?', 'They work on so many levels!'),
    ('work', 'Why did the banker quit his job?', 'He lost interest!'),
    ('work', 'What did the janitor say when he jumped out of the closet?', 'Supplies!'),
    ('work', 'Why did the accountant break up with the calculator?', 'They couldn''t count on each other!'),
    ('work', 'What do you call a person who''s happy on Monday?', 'Retired!'),
    ('work', 'Why did the electrician close his business?', 'There was no spark left!'),
    ('work', 'Why don''t lawyers go to the beach?', 'Cats keep trying to bury them!'),
    ('work', 'Why did the belt get arrested?', 'For holding up a pair of pants!'),
    ('work', 'I got fired from the keyboard factory.', 'I wasn''t putting in enough shifts.'),
    ('work', 'What''s a dentist''s favorite time?', 'Tooth-hurty!'),
    ('work', 'Why did the gardener quit?', 'His celery wasn''t high enough!'),
    ('work', 'Why did the stadium get hot after the game?', 'All the fans left!'),
    ('work', 'I used to work at a blanket factory.', 'But it folded.'),

    ('holiday', 'What do you call an obnoxious reindeer?', 'Rude-olph!'),
    ('holiday', 'Why is Christmas just like a day at the office?', 'You do all the work and the fat guy gets the credit!'),
    ('holiday', 'What do snowmen eat for breakfast?', 'Frosted Flakes!'),
    ('holiday', 'Why did the turkey join the band?', 'Because it had the drumsticks!'),
    ('holiday', 'What does a ghost say on January 1st?', 'Happy Boo Year!'),
    ('holiday', 'Why was the Easter egg hiding?', 'It was a little chicken!'),
    ('holiday', 'What do elves learn in school?', 'The elf-abet!'),
    ('holiday', 'Why did Santa go to music school?', 'To improve his wrapping skills!'),
    ('holiday', 'What''s a vampire''s favorite holiday?', 'Fangsgiving!'),
    ('holiday', 'Why doesn''t Santa eat junk food?', 'It''s bad for his elf!'),
    ('holiday', 'What did one snowman say to the other?', 'Do you smell carrots?'),
    ('holiday', 'Why was the snowman looking through the carrots?', 'He was picking his nose!'),
    ('holiday', 'What do you get when you cross a snowman with a vampire?', 'Frostbite!'),
    ('holiday', 'What''s the best thing to put into a Christmas cake?', 'Your teeth!'),
    ('holiday', 'Why do mummies like Christmas so much?', 'Because of all the wrapping!'),

    ('science', 'Why can''t you trust an atom?', 'They make up everything!'),
    ('science', 'What did the biologist wear on their first date?', 'Designer genes!'),
    ('science', 'Why did the chemist break up with the physicist?', 'They had no chemistry!'),
    ('science', 'What do you call a tooth in a glass of water?', 'A one molar solution!'),
    ('science', 'What''s a physicist''s favorite food?', 'Fission chips!'),
    ('science', 'How did the astronaut serve dinner?', 'On flying saucers!'),
    ('science', 'Why did the electron break up with the proton?', 'It was too negative!'),
    ('science', 'What did Earth say to the other planets?', 'You guys have no life!'),
    ('science', 'Why is the moon so broke?', 'It''s down to its last quarter!'),
    ('science', 'How do you organize a space party?', 'You planet!'),
    ('science', 'What did the thermometer say to the graduated cylinder?', 'You may have graduated, but I have more degrees!'),
    ('science', 'Why are chemists excellent for solving problems?', 'They have all the solutions!'),
    ('science', 'Why did Oxygen go on a date with Potassium?', 'It went OK!'),
    ('science', 'What do you do with a sick chemist?', 'If you can''t helium and you can''t curium, you might as well barium!'),
    ('science', 'Why did the photon check no luggage at the airport?', 'Because it was traveling light!'),

    ('sports', 'Why did the golfer bring two pairs of pants?', 'In case he got a hole in one!'),
    ('sports', 'What lights up a soccer stadium?', 'A soccer match!'),
    ('sports', 'Why do basketball players love donuts?', 'Because they can dunk them!'),
    ('sports', 'What''s a boxer''s favorite drink?', 'Punch!'),
    ('sports', 'Why did the football coach go to the bank?', 'To get his quarterback!'),
    ('sports', 'What do you call a pig that plays basketball?', 'A ball hog!'),
    ('sports', 'Why are baseball games always at night?', 'Because bats sleep during the day!'),
    ('sports', 'What''s a cheerleader''s favorite drink?', 'Root beer!'),
    ('sports', 'Why is Cinderella bad at soccer?', 'She always runs away from the ball!'),
    ('sports', 'What do you call a boomerang that doesn''t come back?', 'A stick!'),
    ('sports', 'Why do soccer players do well in school?', 'They know how to use their heads!'),
    ('sports', 'What animal is best at hitting a baseball?', 'A bat!'),
    ('sports', 'Why was the stadium so cool?', 'It was full of fans!'),
    ('sports', 'What do you call a referee who works at a restaurant?', 'A food critic!'),
    ('sports', 'Why do tennis players never get married?', 'Because love means nothing to them!'),

    ('music', 'What''s a cat''s favorite song?', 'Three Blind Mice!'),
    ('music', 'Why couldn''t the string quartet find their composer?', 'He was Haydn!'),
    ('music', 'What do you call a cow that plays guitar?', 'A moo-sician!'),
    ('music', 'Why did the pianist keep banging his head against the keys?', 'He was playing by ear!'),
    ('music', 'What''s a skeleton''s favorite instrument?', 'The trom-bone!'),
    ('music', 'Why is a piano so hard to open?', 'Because the keys are on the inside!'),
    ('music', 'What do you call a musical insect?', 'A humbug!'),
    ('music', 'What type of music are balloons afraid of?', 'Pop music!'),
    ('music', 'Why did the fish make a good musician?', 'He knew his scales!'),
    ('music', 'What''s a guitar''s favorite cheese?', 'String cheese!'),
    ('music', 'Why do bagpipers walk when they play?', 'To get away from the noise!'),
    ('music', 'What do you call a laughing piano?', 'A Yamahahaha!'),
    ('music', 'What''s a mummy''s favorite type of music?', 'Wrap music!'),
    ('music', 'Why did the music teacher go to jail?', 'For fingering A minor!'),
    ('music', 'What rock band has four guys that don''t sing?', 'Mount Rushmore!'),

    ('family', 'Why did the kid cross the playground?', 'To get to the other slide!'),
    ('family', 'What did the daddy tomato say to the baby tomato?', 'Ketchup!'),
    ('family', 'Why do dads always carry a spare battery?', 'They like to stay positive!'),
    ('family', 'What did the buffalo say when his son left?', 'Bison!'),
    ('family', 'Why did the dad bring a ladder to the bar?', 'He heard the drinks were on the house!'),
    ('family', 'What do you call a dad who fell through the ice?', 'A pop-sicle!'),
    ('family', 'Why do dads tell such bad jokes?', 'Because the punchlines became apparent!'),
    ('family', 'What''s a dad''s favorite candy?', 'Poprocks!'),
    ('family', 'Why did the picture go to jail?', 'Because it was framed!'),
    ('family', 'What do you call a fake dad?', 'A faux pa!'),
    ('family', 'Why did the baby cookie cry?', 'Because its mother was a wafer so long!'),
    ('family', 'What did the mama broom say to the baby broom?', 'Go to sweep!'),
    ('family', 'Why do teenage girls travel in odd numbers?', 'Because they can''t even!'),
    ('family', 'What do you call a sleeping dad?', 'A nap-kin!'),
    ('family', 'Why don''t dads ever play hide and seek?', 'Because good luck hiding when someone always needs something!')
) AS j(cat_slug, setup, punchline)
WHERE c.slug = j.cat_slug;

-- Mark some jokes as featured
UPDATE jokes SET is_featured = true
WHERE id IN (
    SELECT id FROM jokes ORDER BY RANDOM() LIMIT 10
);

-- Set today's daily joke
INSERT INTO daily_jokes (joke_id, featured_date)
SELECT id, CURRENT_DATE FROM jokes ORDER BY RANDOM() LIMIT 1;
